ALTER TABLE `stuff_db`
	ADD CONSTRAINT `STUFF_DB_STUFF_ID_FK` FOREIGN KEY (`stuff_id`) REFERENCES `stuff_meta` (`id`) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE `stuff_license`
	ADD CONSTRAINT `STUFF_LICENSE_STUFF_ID_FK` FOREIGN KEY (`stuff_id`) REFERENCES `stuff_meta` (`id`) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE `stuff_develop_language`
	ADD CONSTRAINT `STUFF_DEVELOP_LANGUAGE_STUFF_ID_FK` FOREIGN KEY (`stuff_id`) REFERENCES `stuff_meta` (`id`) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE `stuff_os`
	ADD CONSTRAINT `STUFF_OS_STUFF_ID_FK` FOREIGN KEY (`stuff_id`) REFERENCES `stuff_meta` (`id`) ON UPDATE CASCADE ON DELETE CASCADE;